# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is automatically generated by CrossSync. Do not edit manually.

"""Metrics-ownership parity tests.

For accelerated RPCs the daemon owns retries *and* metrics — the Python layer
deliberately attaches a handler-less metric (read_row) or skips metrics entirely
(mutate_row), so the client-side metrics handlers must observe nothing for those
calls. The native client, by contrast, records one completed operation per call.
This pins down that ownership boundary so accelerated traffic is never
double-counted by the Python exporter.
"""

import uuid

from google.cloud.bigtable.data._metrics.handlers._base import MetricsHandler
from google.cloud.bigtable.data.mutations import DeleteAllFromRow, SetCell

from . import _harness
from ._base_autogen import AcceleratorTestBase


class _CountingMetricsHandler(MetricsHandler):
    """Records completed operations/attempts so tests can count them."""

    def __init__(self, **kwargs):
        self.completed_operations = []
        self.completed_attempts = []

    def on_operation_complete(self, op):
        self.completed_operations.append(op)

    def on_attempt_complete(self, attempt, _):
        self.completed_attempts.append(attempt)


class TestMetricsParity(AcceleratorTestBase):
    """Client-side metrics fire for native RPCs but not accelerated ones."""

    def _read_and_write(self, table):
        key = f"metrics-{uuid.uuid4().hex}".encode()
        table.mutate_row(
            key,
            SetCell(
                _harness.TEST_FAMILY, b"q", b"v", timestamp_micros=1000 * _harness.MS
            ),
        )
        table.read_row(key)
        table.mutate_row(key, DeleteAllFromRow())

    def test_accelerated_ops_bypass_python_metrics(self, instance_id, table_id):
        """Accelerated read_row/mutate_row emit no client-side metrics; the native
        path emits one completed operation per call."""
        accel_handler = _CountingMetricsHandler()
        native_handler = _CountingMetricsHandler()
        with (
            self._make_client(use_accelerator=True) as accel_client,
            self._make_client(use_accelerator=False) as native_client,
        ):
            with (
                accel_client.get_table(instance_id, table_id) as accel_table,
                native_client.get_table(instance_id, table_id) as native_table,
            ):
                self.assert_accelerator_active(accel_table)
                self.assert_native(native_table)
                accel_table._metrics.add_handler(accel_handler)
                native_table._metrics.add_handler(native_handler)
                self._read_and_write(accel_table)
                self._read_and_write(native_table)
        assert len(native_handler.completed_operations) >= 2, (
            f"native client should record client-side metrics for its RPCs; got {len(native_handler.completed_operations)}"
        )
        assert len(accel_handler.completed_operations) == 0, (
            f"accelerated RPCs must not emit client-side metrics (daemon owns them); got {len(accel_handler.completed_operations)}: {accel_handler.completed_operations}"
        )
